### ISSUE TITLE
Запрос рецензии

### ISSUE THREAD

**Issue by thiefm** [thiefm/isp01_kharyushin_ms_mdk0101#1]
@ToxicTeacher, требуется рецензия на
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/tree/master/self_task/work_11.02.2020/projects/ConsoleApp1

**Comment by ToxicTeacher** [comment]
Замечания
1 Определить метод Swap(), чтобы избавиться от дублирования следующего набора строк кода:
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/d0c4ea303c1a655e9547b9ab3fafcf9103b72682/self_task/work_11.02.2020/projects/ConsoleApp1/ConsoleApp1/ArraySort.cs#L20-L22
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/d0c4ea303c1a655e9547b9ab3fafcf9103b72682/self_task/work_11.02.2020/projects/ConsoleApp1/ConsoleApp1/ArraySort.cs#L44-L46
2 Перед каждым методом добавлять пустую строку:
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/d0c4ea303c1a655e9547b9ab3fafcf9103b72682/self_task/work_11.02.2020/projects/ConsoleApp1/ConsoleApp1/ArraySort.cs#L29-L30
