### ISSUE TITLE
Запрос рецензии

### ISSUE THREAD

**Issue by thiefm** [thiefm/isp01_kharyushin_ms_mdk0101#2]
@ToxicTeacher, требуется рецензия на
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/tree/master/self_task/work_12.02.2020

**Comment by ToxicTeacher** [comment]
Замечания
1 Убрать строки с подключением неиспользуемых пространств имён из каждого файла. Пример:
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/9d6a5c8a734710adf94b8348f2ef23a7bb2deb2f/self_task/work_12.02.2020/projects/Kharyushin_ISP01/Kharyushin_ISP01/Address.cs#L2-L5
2 Для хранения дат использовать экземпляры структуры DateTime, другие типы не подходят. Пример строк с ошибкой:
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/9d6a5c8a734710adf94b8348f2ef23a7bb2deb2f/self_task/work_12.02.2020/projects/Kharyushin_ISP01/Kharyushin_ISP01/Game.cs#L13
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/9d6a5c8a734710adf94b8348f2ef23a7bb2deb2f/self_task/work_12.02.2020/projects/Kharyushin_ISP01/Kharyushin_ISP01/Product.cs#L1
https://github.com/thiefm/isp01_kharyushin_ms_mdk0101/blob/9d6a5c8a734710adf94b8348f2ef23a7bb2deb2f/self_task/work_12.02.2020/projects/Kharyushin_ISP01/Kharyushin_ISP01/Test.cs#L13
